### ISSUE TITLE
Cannot call Get(1) because there are 1 arguments.

### ISSUE THREAD

**Issue by smoothbear** [stretchr/testify#1064]
```go

type _mock struct {
	mock *mock.Mock
}

func Mock(mock *mock.Mock) _mock {
	return _mock{mock: mock}
}

func (m _mock) CreateUser(user *model.User) (*model.User, error) {
	args := m.mock.Called(user)
	return args.Get(0).(*model.User), args.Error(1)
}
```
I gave 0 parameter to args.Get(), But test failed with
```go
--- FAIL: Test_default_CreateUser (0.00s)
panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s). [recovered]
        panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s).
```
How should I resolve this problem?

**Comment by nishanths** [comment]
I ran into the same issue. 

I had incorrectly thought that the numbers in `args.Get(0)`, `args.Get(1)`, etc. correspond to the number of parameters to the mocked method (`user *model.User` above). But the actual issue is that the `Return` call is doesn't have the correct number of return arguments.

```
mockedObj.
  On("CreateUser", ...).
  Return(...)
```
