### ISSUE TITLE
Runtime error - github.com/stretchr/testify/assert/assertions.go:77

### ISSUE THREAD

**Issue by oskarogri** [stretchr/testify#107]
Hi guys,

Warning: might be a totally nooby mistake - in which case I excuse myself profusely in advance.

For the last couple of days I've been trying to use testify assertions. And I get a runtime error and I don't know what I can do to fix it. Here is the code:

``` go
func TestExperience(t *testing.T) {
    assert := assert.New(t)

    exp := 1
    act, err := XPCost(types.OTEasySkill, 1) //func XPCost(types.ObjectType, level int) (int, error)
    assert.Nil(err)
    assert.Equal(exp, act)

    _, err2 := XPCost(types.OTRoom, 1) 
    assert.Nil(err2) // Line 30.
}
```

This results in the following output:

``` go
--- FAIL: TestExperience (0.00 seconds)
panic: runtime error: index out of range [recovered]
    panic: runtime error: index out of range

goroutine 3 [running]:
github.com_stretchr_testify_assert.CallerInfo
    /go/src/github.com/stretchr/testify/assert/assertions.go:77
github.com_stretchr_testify_assert.Fail
    /go/src/github.com/stretchr/testify/assert/assertions.go:155
github.com_stretchr_testify_assert.Nil
    /go/src/github.com/stretchr/testify/assert/assertions.go:271
github.com_stretchr_testify_assert.Nil.pN45_github.com_stretchr_testify_assert.Assertions
    /go/src/github.com/stretchr/testify/assert/forward_assertions.go:65
github.com_oskarogri_adventure.TestExperience
    /go/src/github.com/oskarogri/adventure/adventure_test.go:30

goroutine 1 [chan receive]:
main.main
    /tmp/go-build478129884/github.com/oskarogri/adventure/_test/_testmain.go:47
exit status 2
FAIL    github.com/oskarogri/adventure  0.027s
```

I'm assuming I'm not using the package correctly, and I need direction. From all the examples I've seen, this should work and I'm lost to why it isn't.

oskarogri

**Comment by ernesto-jimenez** [comment]
@oskarogri did you get some clarification on this?

I'm going through all open issues and saw this was left hanging :)

**Comment by oskarogri** [comment]
Hi. I ended up not using this package for a few months. The code base this was written for is looong gone. I'm using the package again now days and I can't replicate the error. Sorry :/

**Comment by georgelesica-wf** [comment]
Hello, my name is George. I've recently taken over maintenance of Testify and
I'm excited to help the project move forward.

In order to improve responsiveness and promote contributions to the Testify
project, I have decided to close pull requests and issues that haven't had any
activity in several months and do not appear to address critical bugs.

If you would still like to see your pull request or issue addressed, I am happy
to help! All you have to do is re-open and update it to reflect the current
state of the master branch. Once that is done, I will triage and recruit
reviewers as-needed.

If you have questions, please feel free to reach out. Thank you for your
interest in improving the Testify project!
