### ISSUE TITLE
If a matcher panics and AssertExpectations has been deferred, a hang occurs

### ISSUE THREAD

**Issue by cchalm** [stretchr/testify#1155]
In the code below, the test case TestMatcherPanic hangs. To reproduce the hang, two conditions must be met:
1. AssertExpectations is deferred
2. An argument matcher panics

```
import (
	"testing"

	"github.com/stretchr/testify/mock"
)

type Mock struct {
	mock.Mock
}

func (_m *Mock) F() {
	_m.Called()
}

func TestMatcherPanic(t *testing.T) {
  m := &Mock{}
  defer m.AssertExpectations(t)

  matcher := mock.MatchedBy(func(_ interface{}) bool {
    panic("test")
  })
  m.On("F", matcher)

  m.F()
}
```

**Comment by brackendawson** [comment]
I think this is because the `Called()` ends up locking a mutex [here](https://github.com/stretchr/testify/blob/acba37e5db06f0093b465a7d47822bf13644b66c/mock/mock.go#L391), then the panic goes unhandled, then the deferred `AssertExpectations()` runs and tried to lock the same mutex [here](https://github.com/stretchr/testify/blob/acba37e5db06f0093b465a7d47822bf13644b66c/mock/mock.go#L498).

Basically [this](https://go.dev/play/p/PYXGu4jlLDE) is happening:
```go
package main

import "sync"

func main() {
	m := sync.Mutex{}
	defer func() { m.Lock() }()
	m.Lock()
	panic("oh no")
	m.Unlock()
}
```

I think [this] call needs to be wrapped in a function with a deferred recovery that unlocks the mutex and delares the function call unexpected because panic "blah" occurred.

**Comment by cfiderer** [comment]
This also happens when a `nil` argument is matched against an `AnythingOfTypeArgument` expectation: the internal `panic` is not handled, the test unwinds (with `m.mutex` already locked), and AssertExpectations() tries to lock `m.mutex` again.
