### ISSUE TITLE
Release 1.7.2 causes go vet errors when embedding suite.Suite

### ISSUE THREAD

**Issue by AndreasKl** [stretchr/testify#1199]
Our dependapot builds started to fail for some services. We are embedding `suite.Suite` to create custom integration test suites.

```
type IntegrationTester struct {
	suite.Suite
}
```

With the 1.7.2 release and due to adding a [sync.Mutex](https://github.com/stretchr/testify/commit/a409ccf19e17d8a90156521ce71c5e8ef8f6bca8) `go vet` now fails on this code base.

```
go vet ./...
# github.com/snabble/...
./integration_test.go:17:9: Test_Tokenize passes lock by value: github.com/snabble/...IntegrationTester contains github.com/stretchr/testify/suite.Suite contains sync.RWMutex
```

**Comment by daniel-meyer-dme** [comment]
We faced the same issue upgrading to 1.7.2. Tried some approaches to fix this but found no way which wouldn't change the way Suite is used so far.

**Comment by drichelson** [comment]
I'm seeing this issue on 1.8.0. It looks like the the [non-pointer lock is still on master branch](https://github.com/stretchr/testify/blob/master/suite/suite.go#L25)

May we re-open this?

**Comment by brackendawson** [comment]
The change was [reverted](https://github.com/stretchr/testify/pull/1212) because it caused a lot of panics (issues linked in PR). I don't expect this mutex to evert be made into a pointer again. Re-opening this issue would be valid but the fix needs to be different. I think this would be fixed by https://github.com/stretchr/testify/pull/1109 which is an API change in suite that is needed to fix multiple concurrency issues, it would have to go in a testify v2.

**Comment by drichelson** [comment]
Thanks for the explanation @brackendawson ! I don't have permissions to re-open the issue, so will you please do it so it doesn't get lost?

**Comment by drichelson** [comment]
For anyone using golangci-lint this item in the `exclude` section bypasses these failures:
```
    - 'github.com\/stretchr\/testify\/suite\.Suite contains sync\.RWMutex'
```
