### ISSUE TITLE
IsEmpty does not check for empty structs of the same type

### ISSUE THREAD

**Issue by dkdodson3** [stretchr/testify#123]
I looked at your IsEmpty function to see if I could find a way to check to see if the struct is of the same type and empty. Figured out how to do it with reflection and thought I would share...

```go
package main

import ( 
    "fmt"
    "reflect"
)

type ContainerData struct {
    ContainerUrl string `json:"container_url"`
    AckUrl       string `json:"ack_url"`
}

func main() {
    blah := ContainerData {
        ContainerUrl : "consul-kv://web/containers/abc123",
        AckUrl : "http://requestb.in/11u0wr51",
    }

structType := reflect.TypeOf(blah)
structPointer := reflect.New(structType)
structValue := structPointer.Elem()
structValueInterface := structPointer.Interface()
intPtr := reflect.New(reflect.TypeOf(blah)).Elem().Interface()


fmt.Println(blah)
fmt.Println(structType)
fmt.Println(structPointer)
fmt.Println(structValue)
fmt.Println(structValueInterface)
fmt.Println(intPtr)
fmt.Println(reflect.TypeOf(intPtr))
}
```

**Comment by matryer** [comment]
That’s very cool

**Comment by georgelesica-wf** [comment]
Hello, my name is George. I've recently taken over maintenance of Testify and
I'm excited to help the project move forward.

In order to improve responsiveness and promote contributions to the Testify
project, I have decided to close pull requests and issues that haven't had any
activity in several months and do not appear to address critical bugs.

If you would still like to see your pull request or issue addressed, I am happy
to help! All you have to do is re-open and update it to reflect the current
state of the master branch. Once that is done, I will triage and recruit
reviewers as-needed.

If you have questions, please feel free to reach out. Thank you for your
interest in improving the Testify project!
