### ISSUE TITLE
Are assertions thread-safe?

### ISSUE THREAD

**Issue by gavv** [stretchr/testify#1340]
Hi!

Are testify assertions thread safe? Can I call assert.Xxx and require.Xxx from multiple goroutines?

I know that testing.FailNow and friends can be called only from test's goroutine. But does testify place any additional limitations on top of that?

Sorry if it was asked already, I didn't find any information in issues and docs.

Thanks for this great library!

**Comment by brackendawson** [comment]
As you have mentioned, you should not use require.Xxx functions outside of the goroutine running the test funciton because require ultimately calls testing.FailNow.

The assertions are stateless, so they impose no additional concurrency implications so long as the arguments you pass into them are not shared.

The mock library is not stateless and does have bugs in this area, such as #1020 and #1128.

**Comment by gavv** [comment]
Thanks!
