### ISSUE TITLE
wall clock

### ISSUE THREAD

**Issue by yonesko** [stretchr/testify#1510]
Have an annoying issue comparing structs with time:
```go
package main

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

type A struct {
	T time.Time
}

func Test(t *testing.T) {
	now := time.Now()
	a := A{T: now}
	marshal, _ := json.Marshal(a)
	var aParsed A
	json.Unmarshal(marshal, &aParsed)
	assert.Equal(t, a, aParsed)
}
```
Output:
```
        	Error:      	Not equal: 
        	            	expected: repository.A{T:time.Date(2023, time.November, 23, 12, 7, 10, 872457000, time.Local)}
        	            	actual  :     repository.A{T:time.Date(2023, time.November, 23, 12, 7, 10, 872457000, time.Local)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,4 +2,4 @@
        	            	  T: (time.Time) {
        	            	-  wall: (uint64) 13929602241381049128,
        	            	-  ext: (int64) 3371626,
        	            	+  wall: (uint64) 872457000,
        	            	+  ext: (int64) 63836327230,
        	            	   loc: (*time.Location)({
        	Test:       	Test
--- FAIL: Test (0.00s)

Expected :repository.A{T:time.Date(2023, time.November, 23, 12, 7, 10, 872457000, time.Local)}
Actual   :repository.A{T:time.Date(2023, time.November, 23, 12, 7, 10, 872457000, time.Local)}
<Click to see difference>


FAIL

Process finished with the exit code 1
```

**Comment by dolmen** [comment]
I don't understand your issue. Please post a self-contained example that reproduces your issue using this template: https://go.dev/play/p/AsRNcxCRdWx

**Comment by yonesko** [comment]
I have updated the first comment

**Comment by dolmen** [comment]
The [Testify API](https://pkg.go.dev/github.com/stretchr/testify/assert) is very comprehensive. Have you tried the other `Equal` functions? Please expand your test code to show the issue you have with the other functions.

By the way, this isn't a support forum. Issues are for reporting bugs or discussing enhancements. There are [more appropriate places](https://go.dev/help) for asking for help.

**Comment by yonesko** [comment]
This is not support^ this is bug

**Comment by tscales** [comment]
similar issue as #1461. This should be resolved whenever a new release is cut.

**Comment by KKKZOZ** [comment]
i have met with this too, please release a new package asap

**Comment by gabriel-vasile** [comment]
> similar issue as #1461. This should be resolved whenever a new release is cut.

It's a little different. Here `T` time is a field in a struct, meaning the [equality comparison defaults to `reflect.DeepEqual`](https://github.com/tscales/testify/blob/154621cde0cd207381004fdf2abb46f880286cac/assert/assertions.go#L58-L81).
New release will not fix this issue.

**Comment by brackendawson** [comment]
Testify is correct, they are not equal. The behaviour of actual is demonstrably different to the behaviour of expected.

If you only care that they have the same time, then use [WithinDuration](https://pkg.go.dev/github.com/stretchr/testify/assert#WithinDuration):
```go
package main

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

type A struct {
	T time.Time
}

func Test(t *testing.T) {
	now := time.Now()
	a := A{T: now}
	marshal, _ := json.Marshal(a)
	var aParsed A
	json.Unmarshal(marshal, &aParsed)
	assert.WithinDuration(t, a.T, aParsed.T, 0)
}
```

**Comment by yonesko** [comment]
How to compare not times but a structure with time fields ?

**Comment by brackendawson** [comment]
> How to compare not times but a structure with time fields ?

You'll need to either test the fields individually or write an equality test helper function for your struct, for what you consider to be equal. time.Time values are not the only examply where this becomes necessary, another common one is slice type fields where you only care about the elements matching and not the order. The fields literally aren't equal but you can't use EqualElements on a struct.

Another option may be to use `time.Now().Truncate(0)` as your test input, this strips the wall time.

 I'm afraid we can't call this a bug because the behaviour of Equal is as documented according to the [package docs](https://pkg.go.dev/github.com/stretchr/testify/assert#Equal) and the [Go spec](https://go.dev/ref/spec#Comparison_operators), and to change the bahaviour would be a breaking change. What if someone's test depends on the wall time difference between time.Time values?

If you can reason that this change should be made, or you can propose a good design for a compatible change that isn't `assert.SortOfEqual` please comment and I will re-open the issue.
