### ISSUE TITLE
Mock method invoking assertion fails if method containS function type paramenter

### ISSUE THREAD

**Issue by AlexLuya** [stretchr/testify#159]
Hello,
       As you can see,two method invokings are identical,but I still got error,
````golang   
 mock: Unexpected Method Call
    -----------------------------
     ShareRecordsCreatedBy(string,string,func(string) bool)
                0: user-owner
                1: user-creator
                2: 0x4e4e60
    
    The closest call I have is: 
    
    ShareRecordsCreatedBy(string,string,func(string) bool)
                0: user-owner
                1: user-creator
                2: 0x4e4e60
   ````

**Comment by ernesto-jimenez** [comment]
@AlexLuya can you share your failing test?

**Comment by ernesto-jimenez** [comment]
Ok, the bug is in `ObjectsAreEqual`.

It relies on `reflect.DeepEqual`, and according to the methods documentation:
> Functions are equal only if they are both nil.

**Comment by ernesto-jimenez** [comment]
Had another look, I can make the test pass by adding the following check to `ObjectsAreEqual`

```go
ev := reflect.ValueOf(expected)
av := reflect.ValueOf(actual)
if ev.Kind() == reflect.Func && av.Kind() == reflect.Func && ev.Pointer() == av.Pointer() {
  return true
}
```

**However**, according to `Pointer()`'s docs: 
> If v's Kind is Func, the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely. The only guarantee is that the result is zero if and only if v is a nil func Value.

Saw although the test passes, it's not guaranteed to pass which means the behaviour might be broken in certain cases, certain platforms or in the future.

Looking at the `reflect.DeepEqual` implementation, they already have a comment when comparing functions, which might be due to the `Pointer()` limitations:
```go
if v1.IsNil() && v2.IsNil() {
	return true
}
// Can't do better than this:
return false
```

I'm going to check if at least the mock could be defined with `AnythingOfType`.

**Comment by ernesto-jimenez** [comment]
@AlexLuya check Pull Request #160 to see if that would be OK.

**Comment by ernesto-jimenez** [comment]
The solution is to use AnythingOfType in the expectation:

```go
m.On("ShareRecordsCreatedBy", "user-owner", "user-creator", mock.AnythingOfType("func(string) bool"))
```

**Comment by AlexLuya** [comment]
On this solution,only function literal will be check,and what value has been used to invoke this function won't be checked.

**Comment by ernesto-jimenez** [comment]
@AlexLuya I'm afraid that's the best we can do with the reflect package.

**Comment by AlexLuya** [comment]
Thanks.
