### ISSUE TITLE
Unable to test concurrent objects

### ISSUE THREAD

**Issue by ANPez** [stretchr/testify#167]
Because of the changed described in #55, my tests fail randomly when making parallel calls to the same object. My object supports that, but the lock is serializing the calls.

**Comment by ernesto-jimenez** [comment]
@ANPez are you up for doing a PR on this?

I ran into the same issues mocking a gorilla websocket which had two goroutines one calling WriteJSON and the other oner calling ReadJSON. It was quicker for me to do a fast workaround, but it would be gret to get this fixed :)

**Comment by ANPez** [comment]
I was in the exact same situation as you, just fixed it :)

**Comment by georgelesica-wf** [comment]
Hello, my name is George. I've recently taken over maintenance of Testify and
I'm excited to help the project move forward.

In order to improve responsiveness and promote contributions to the Testify
project, I have decided to close pull requests and issues that haven't had any
activity in several months and do not appear to address critical bugs.

If you would still like to see your pull request or issue addressed, I am happy
to help! All you have to do is re-open and update it to reflect the current
state of the master branch. Once that is done, I will triage and recruit
reviewers as-needed.

If you have questions, please feel free to reach out. Thank you for your
interest in improving the Testify project!
