### ISSUE TITLE
`Eventually` functions documentation is misleading as waitFor and tick are swapped in the example

### ISSUE THREAD

**Issue by delca85** [stretchr/testify#1677]
## Description

Documentation of `EventuallyWithT` and `EventuallyWithTf` functions (in both [require](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/require) or [assert](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/assert) package) is misleading, as the sample code swaps `waitFor` and `tick` args in the call. 

## Step To Reproduce

Go to [assert.EventuallyWithT](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/assert#EventuallyWithT) docs and look at the example, it shows `1*time.Second`, that is supposed to be the `tick` as 1st argument that should be `waitFor`.
Same thing for [assert.EventuallyWithTf](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/assert#EventuallyWithTf), [require.EventuallyWithT](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/require#EventuallyWithT) and [require.EventuallyWithTf](https://pkg.go.dev/github.com/stretchr/testify@v1.9.0/require#EventuallyWithTf).

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! What file(s) should be edited? This [search query](https://github.com/search?q=repo%3Astretchr%2Ftestify+%22asserts+that+given+condition+will+be+met+in%22&type=code) shows five files but I'm unsure if they all should be edited especially since some of them have a comment at the top to not edit --> `// Code generated with github.com/stretchr/testify/_codegen; DO NOT EDIT.`

**Comment by brackendawson** [comment]
Only edit files without the DO NOT EDIT header. To change the rest you run `go generate ./...`.

**Comment by brackendawson** [comment]
Thanks for your efforts, however I now see this was actually fixed in #1588 but that hasn't been released yet.

I do plan to make a v1.10.0 release soon. I have an ordered list of testify tasks for me to do and making the release is currently second on that list.
