### ISSUE TITLE
Two suggestions about error message readability.

### ISSUE THREAD

**Issue by AlexLuya** [stretchr/testify#178]
Hello,I got an error message like this:

````go
    Test Panicked
        
    mock: Unexpected Method Call
    -----------------------------
    
    ToCache(string,*initdata.InitData)
                0: user-001
                1: &{SIGNIN [] [] [] []  0 [] [] [] [{0  0 remind-001   0  []}] [] session-newClient 2 0xc20810e360 <nil> []}
    
    The closest call I have is: 
    
    ToCache(string,*initdata.InitData)
                0: user-001
                1: &{SIGNIN [] [] [] []  0 [] [] [] [] [] session-newClient 0 0xc20810e1b0 <nil> []}

````
First :
Many times,I will wondering: what is expectation,what is actual operation?
if the description was modified from

````go
    Test Panicked
        
    mock: Unexpected Method Call
    -----------------------------
   ......
    The closest call I have is: 
    ......
````

 to:

````go
    Test Panicked
        
  By mocking,method should be called like
    -----------------------------
   ......
    But actually, it was called like this(guessed): 
````
it will save a little bit time to guessing.

Second problem is all field names lost if parameter is a struct.
From error message,in the first glance,I can see they are different,but I can't found which fields are different,so if fields name got added,it will be much easier to locate differences.

**Comment by ernesto-jimenez** [comment]
Hi @AlexLuya,

I just made the change to show the struct fields.

With regards to the text in the error. That error tells you that you called the a method in the mock that it was unexpected (hence the "Unexpected method call", rather than how it should be called.

The information about the closest call is just a little helper when debugging the error so that if you have set an expectation with `On(...).Return(...)` that is close to the way you called the mock, you can see what the difference is.
