### ISSUE TITLE
Misleading error message with Implements assertion

### ISSUE THREAD

**Issue by agonzalezro** [stretchr/testify#234]
Disclaimers:

- I don't know if this behaviour is by design.
- I understand why is happening but I think that it could be a little bit more verbose with the error.

Using this assertion:

    assert.Implements(t, (*TheInterface)(nil), &TheStruct{})

Everything works fine, but if I forget the `&` the error that I will get is:

    Error:		Object must implement TheInterface

Which in my opinion is a little bit misleading.

What do you think? Feel free to close the issue if this behaviour is expected by design.

**Comment by ernesto-jimenez** [comment]
@agonzalezro out of curiosity: why do you find it misleading? Is it because it seems that you are passing a struct of type Object?

It can be changed to "TheStruct must implement TheInterface" easily, if you make a PR I would be happy to merge it :)

Just add a `%T` to the message in: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L211

**Comment by agonzalezro** [comment]
Hi Ernesto,

no, I think that I didn't explain myself properly. Check this example:

`main.go`
```
package main

type TheInterface interface {
	dosomething()
}

type TheStruct struct{}

func (s *TheStruct) dosomething() {}

func main() {}
```

`main_test.go`
```
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSomething(t *testing.T) {
	assert.Implements(t, (*TheInterface)(nil), &TheStruct{})
}

func TestMisleading(t *testing.T) {
	assert.Implements(t, (*TheInterface)(nil), TheStruct{})
}
```

`output`
```
$ go test .
--- FAIL: TestMisleading (0.00s)
        Error Trace:    main_test.go:14
        Error:          Object must implement main.TheInterface

FAIL
FAIL    github.com/jobandtalent/geoservice/asdasd       0.009s
```

Also, writting this test I realise that if your method is not a pointer: `func (s TheStruct) dosomething() {}` both tests will be ok.

**Comment by ernesto-jimenez** [comment]
Yep, I got that, but I find that error to be accurate, isn't it?

What do you find misleading about that error?

**Comment by agonzalezro** [comment]
IMO it should tell you that it's expecting a pointer to a struct in the second case, if not you will think that it's not being implemented becase you forgot to implement some method and not because you forgot to write `&`.

But perhaps this is just a personal preference since you don't seem to agree with it.

**Comment by ernesto-jimenez** [comment]
It didn't occur to me you meant we should reflect on the value and see whether a pointer to the same value would actually satisfy the interface.

I believe that trying to guess what the user wanted to send is out of the scope of the package. Also, there are other cases why that test might fail. E.g: you were satisfying the interface by embedding a field and you just named it rather than embedding it.

In my opinion, showing more details about why an assertion fails is OK, but trying to guess what the user wanted to do is trickier and might be more misleading in some cases.

**Comment by agonzalezro** [comment]
Yeah, I expected that this could be the explanation. Feel free to close the issue.

I am happy to PR the change to `%T` if you still need it.

Thanks for the quick feedback!

**Comment by ernesto-jimenez** [comment]
@agonzalezro if you want to make it, that would be cool, otherwise I'll just rename this issue and leave it open until I make the change :)

**Comment by agonzalezro** [comment]
I've create a PR for the change you mentioned @ernesto-jimenez. I will close this issue.
