### ISSUE TITLE
Using mock with arguments involving pointers seems to always not match

### ISSUE THREAD

**Issue by dominicbarnes** [stretchr/testify#271]
So, I'm setting up a mock for a func that accepts a struct as an argument. However, when the property in question is part of a sub-struct that is a pointer, it is never considered a match and I always get a message like this:

```
Call(string,*setting.Setting,*[]setting.Setting)
		0: "DatabaseSetting.GetAll"
		1: &setting.Setting{ID:"", Version:(*int)(nil), DatabaseID:"", WorkspaceID:"", ProjectOverrides:map[string]*setting.ProjectOverride(nil), CreatedAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Frequency:(*int)(nil), CustomFrequency:(*bool)(nil), Enabled:(*bool)(nil), Settings:map[string]interface {}(nil), Vacuum:(*setting.Vacuum)(0xc820014a50), StackName:(*string)(nil)}
		2: &[]setting.Setting{}

The closest call I have is:

Call(string,*setting.Setting,string)
		0: "DatabaseSetting.GetAll"
		1: &setting.Setting{ID:"", Version:(*int)(nil), DatabaseID:"", WorkspaceID:"", ProjectOverrides:map[string]*setting.ProjectOverride(nil), CreatedAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, Frequency:(*int)(nil), CustomFrequency:(*bool)(nil), Enabled:(*bool)(nil), Settings:map[string]interface {}(nil), Vacuum:(*setting.Vacuum)(0xc820014a00), StackName:(*string)(nil)}
		2: "mock.Anything"
```

The difference cited here is close to the end: `Vacuum:(*setting.Vacuum)(0xc820014a50)` vs `Vacuum:(*setting.Vacuum)(0xc820014a00)`.

It would appear that it considers the items unequal since the pointers are for different addresses. (fwiw, this same issue affects `assert.EqualValues()`)

I would imagine that a strict equality would expect the pointers to look at the same address. However, something that should be more loose like this I would expect to compare the values of the 2 different structs.

**Comment by ernesto-jimenez** [comment]
Hi @dominicbarnes,

The matching is done with `assert.ObjectsAreEqual` which in turn uses `reflect.DeepEqual`.

If you need more control over the matching, you can define your own matching function for that argument with [`mock.MatchedBy`](https://godoc.org/github.com/stretchr/testify/mock#MatchedBy).

**Comment by dominicbarnes** [comment]
Ah, so is this the expected behavior from `reflect.DeepEqual` then? (ie: it considers pointers unequal if they are for different addresses?)

**Comment by dominicbarnes** [comment]
Whoops, I found the problem. Totally my fault!

**Comment by vkdive** [comment]
@dominicbarnes can you please share the solution??

**Comment by FrancoisChastel** [comment]
It can come from numerous of reason, one of those may be that you are using `.Once()` or something at the definition of your mocked function. It will specify that the mocked function should return the result only x time.

If your code using this mock is calling it more than the number of time (once in this case) defined this error will occur !

**Comment by Dirk-Scholten** [comment]
I ran into this issue as well.  My issue was that I had an object that was going to be returned by the first mocked function as a pointer and then used in the second mocked function. 

To create the mocks for these functions I created an instance of the object (as non pointer, since the first mocked function was going to return the object as a pointer for me). And then I used the original object that I created in my test as parameter in the mock. So the mock was expecting a non-pointer version because I never made it a pointer in my test (I let the mocked function do that). 

Below is a small code sample to hopefully explain the situation a bit better: 
`request := http.Request{}

httpClientMock.On("NewRequest", "POST", requestUrl, bytes.NewBuffer([]byte("msg")).Return(&request, nil)

httpClientMock.On("SendRequest", request).Return(resp, nil)`

That was my first version of the code. I was using the 'request' variable in both mocks, once as a return value and once as a parameter. The function "NewRequest" would make this a pointer already (has to comply with the httpClientMock interface so I didn't have the freedom to change that) so that's why I didn't create a pointer of the request object in the first place. 

Solution: 
`request := http.Request{}
 request2 := &http.Request{}

httpClientMock.On("NewRequest", "POST", requestUrl, bytes.NewBuffer([]byte("msg")).Return(&request, nil)

httpClientMock.On("SendRequest", request2).Return(resp, nil)`

Pretty self explanatory I think. I simply made a second variable that I did turn into a pointer so that I could use that in the second function. 

Of course if you have any changes going on to the request object in between these two function calls you would have to modify your "request2" variable to reflect those changes. I don't feel like this is an ideal solution but it solved my issue.

**Comment by just-chillin** [comment]
I also had this issue. 

For me I was able to fix it by calling `sort.SliceStable` on the input arguments to my mock. The repository I am working on is open source, so you can see the commit fixing the issue here https://github.com/DataDog/datadog-agent/pull/17448/commits/87b004dd307cb1d9973d2a2ade6b3ceeca20a9c1.

I think the issue here is with the test output produced by testify. For me, when my input slice is out of order I get a result like so:
```
Difference found in argument 1:

--- Expected
+++ Actual
@@ -1,2 +1,8 @@
 ([]*workloadmeta.ProcessEntity) (len=2) {
+ (*workloadmeta.ProcessEntity)({
+  pid: (int32) 1001,
+  language: (*languagemodels.Language)({
+   Name: (languagemodels.LanguageName) (len=6) "python"
+  })
+ }),
  (*workloadmeta.ProcessEntity)({
@@ -6,8 +12,2 @@
   })
- }),
- (*workloadmeta.ProcessEntity)({
-  pid: (int32) 1001,
-  language: (*languagemodels.Language)({
-   Name: (languagemodels.LanguageName) (len=6) "python"
-  })
  })

Diff: 0: PASS:  ([]*workloadmeta.ProcessEntity=[]) == ([]*workloadmeta.ProcessEntity=[])
        1: FAIL:  ([]*workloadmeta.ProcessEntity=[0xc000439f60 0xc000439f70]) != ([]*workloadmeta.ProcessEntity=[0xc000439eb0 0xc000439ed0])
```

Without knowing what the issue was, it initially appeared to me that testify was saying that the two inputs are different because their pointers reference different addresses, not that the order of the slice is incorrect.

In my case, the issue was subtle - the reason this bug occured is because go randomizes the order of a map when you loop over it using a `range` clause, which means that these values wouldn't necessarily be `append()`-ed to the list in the same order.
