### ISSUE TITLE
Spew Dependency Not Available

### ISSUE THREAD

**Issue by tomdeering-wf** [stretchr/testify#272]
Testify has the godep ```github.com/davecgh/go-spew/spew```, but this gives a 404.

**Comment by ernesto-jimenez** [comment]
@tomdeering-wf that's because of githubs links. `github.com/strechr/testify/assert` also gives a 404, since links to a repo's content need information about the branch to check the content. The package is available in [`github.com/davecgh/go-spew`](github.com/davecgh/go-spew).

Also, [spew is vendored](https://github.com/stretchr/testify/tree/master/vendor/github.com/davecgh/go-spew/spew) within testify in case the repo actually gets deleted for real.

**Comment by tomdeering-wf** [comment]
@ernesto-jimenez, thanks, I noticed that I could use the vendored version of spew within testify. But the GitHub source (that you linked to) seems to no longer be available. If I follow your link I still get the 404.

**Comment by ernesto-jimenez** [comment]
@tomdeering-wf it is available in https://github.com/davecgh/go-spew/tree/master/spew :)

Notice that github needs the `/tree/master` between `/go-spew` and `/spew` to serve the info on the website :)

The same happens with testify: http://github.com/stretchr/testify/assert returns 404 because the url is http://github.com/stretchr/testify/tree/master/assert but the package is `github.com/stretchr/testify/assert`

**Comment by tomdeering-wf** [comment]
Ok, thanks for making it very clear :)
