### ISSUE TITLE
Feature Request: mock.AssertExpectations should cause a test to fail

### ISSUE THREAD

**Issue by dominicbarnes** [stretchr/testify#276]
Currently, `mock.AssertExpectations()` returns a `bool` and it logs to stdout/stderr with it's findings. This caught me off guard, because I expected it to cause my tests to fail if all the calls weren't made. There are 2 reasons I have this expectation:

 1. it's got `Assert` in the method name, which generally means it's a test assertion that should be satisfied to consider a test green
 2. it's receiving the `t testing.T` argument, like other `assert` methods which generally accept that so they can indicate a failed test

Right now, you have to do this in order to make a test fail:

```go
assert.True(t, mock.AssertExpectations(t))
```

This seems unnecesarily verbose, and I'm not sure what the use case is for calling `mock.AssertExpectations` without wanting to fail a test. If this method is purely intended for reporting, it should probably be named `mock.ReportExpectations` or something else.

My proposal is to make allow this usage instead:

```go
mock.AssertExpectations(t)
```

**Comment by ernesto-jimenez** [comment]
Hi Dominic,
Tests should be failing in that case. Can you share a test with the wrong behaviour?
Thanks!Ernesto






On Thu, Feb 18, 2016 at 11:10 AM -0800, "Dominic Barnes" <notifications@github.com> wrote:












Currently, mock.AssertExpectations() returns a bool and it logs to stdout/stderr with it's findings. This caught me off guard, because I expected it to cause my tests to fail if all the calls weren't made. There are 2 reasons I have this expectation:


it's got Assert in the method name, which generally means it's a test assertion that should be satisfied to consider a test green
it's receiving the t testing.T argument, like other assert methods which generally accept that so they can indicate a failed test




Right now, you have to do this in order to make a test fail:

assert.True(t, mock.AssertExpectations(t))



This seems unnecesarily verbose, and I'm not sure what the use case is for calling mock.AssertExpectations without wanting to fail a test. If this method is purely intended for reporting, it should probably be named mock.ReportExpectations or something else.



My proposal is to make allow this usage instead:

mock.AssertExpectations(t)

**Comment by dominicbarnes** [comment]
Sorry about that, this was my fault entirely. This library is working as design.
