### ISSUE TITLE
assert.Len and require.Len are not consistent with rest of the API

### ISSUE THREAD

**Issue by mechmind** [stretchr/testify#289]
While all tests that compare computed value with reference one take arguments in order "expected, than actual" the Len test accepts actual object first and expected object length then. That's sad.

**Comment by ernesto-jimenez** [comment]
@mechmind, yes, there's a bunch of inconsistencies like that from the initial development.

Unfortunately, making the API consistent will require breaking changes since we'll have to change the signature of the exported functions.

I wish there's was a better story for package versioning to address those things and offer a clear upgrade path people would be aware of.

**Comment by mechmind** [comment]
Do you consider publishing on gopkg.in or similar repository with versioning?

**Comment by ernesto-jimenez** [comment]
That is virtually like forking the project. You have different import paths for each version and the only way for people to be aware of new versions is to check on repository and see the install instructions.

How often do people do that?

**Comment by anacrolix** [comment]
You can switch parameter ordering easily on existing code with gofmt.

**Comment by soroushjp** [comment]
+1 for a gopkg.in versioning with breaking version bumps.

**Comment by ernesto-jimenez** [comment]
I created a different issue to discus new major versions: #306
