### ISSUE TITLE
mocks - gomega/ginkgo Eventually equivalent

### ISSUE THREAD

**Issue by ghost** [stretchr/testify#305]
When migrating to go 1.6, i've encountered several flaky tests in the following case:
We use objects that create their own go routine that call mocked objects upon receiving an object on a channel. Our tests trigger the go routine to process the object by sending an object to a channel. 

```
foo := &mock.Foo{}
foo.On("Foo", nil).Once()
bar := NewBar(foo) //this runs a go routine that waits on a channel
bar.handleFoo(nil) //sends nil on bar's channel
foo.AssertExpectations()
```

In go 1.4, after sending nil on the channel, the test goroutine yielded and everything was fine (well not really but our test cases are usually fast and minimal). In go 1.6 it isn't the case. Since handleFoo is asynchronous we have no way of knowing when it's done executing. It would be cool to either have a channel that is signaled after the assertions are met or some sort of statement similar to Eventually in ginkgo which samples a certain condition until it's met or times out.

**Comment by matryer** [comment]
If your test code is interested in when NewBar has finished executing, then might the users of your code also be interested? In which case, perhaps adding a done channel to your own code is the way to go, and the test code could block waiting for it.

In test code, doing something like this is a nice way to assert that the done channel is working as expected too, and the process doesn’t take too long:

```
select {
	case <-done:
		// continue
	case <-time.After(1 * time.Second):
		// timed out
		assert.Fail(t, “timed out”)
}
```

**Comment by roee-indegy** [comment]
We only have need for checking this for testing purposes - we don't want it to impact production code. Besides this is a common pattern in our code, adding it to all the structs that work similarly is a pain in the ass.

**Comment by matryer** [comment]
I seriously think its dangerous to have unsupervised goroutines running. What do others think?

**Comment by ernesto-jimenez** [comment]
@roee-indegy you could do something like this:

```go
foo := &mock.Foo{}
done := make(chan struct{})
foo.On("Foo", nil).Once().Run(func(mock.Arguments) { close(done) })
bar := NewBar(foo) //this runs a go routine that waits on a channel
bar.handleFoo(nil) //sends nil on bar's channel
select {
case <-done:
case <-time.After(1 * time.Second):
	assert.Fail(t, “timed out”)
}
foo.AssertExpectations()
```

`Run` and `WaitUntil` can help test concurrent code where you need some fine grained control over the order.

As @matryer mentioned, you must still make sure all your goroutines are under control. e.g: does `Bar` have a `Close` method that would drain any queued up calls, tear down goroutines, and block until it's done?

In that case your code would be:

```go
foo := &mock.Foo{}
foo.On("Foo", nil).Once()
bar := NewBar(foo) //this runs a go routine that waits on a channel
bar.handleFoo(nil) //sends nil on bar's channel
bar.Close()
foo.AssertExpectations()
```

**Comment by roee-indegy** [comment]
@ernesto-jimenez it's easy to solve when you have 1 mock calling 1 function, and not several mocks that are supposed to call many functions.
In the 2nd snippet there's still a race between closing and handling foo. 
Anyway, i didn't mean to start a debate about how to properly manage go routines - im just suggesting a feature that can be helpful when calling functions asynchronously. We've managed to work around the issue using various methods, but having a built in feature in the mock library would've made our lives easier.

**Comment by ernesto-jimenez** [comment]
@roee-indegy those primitives can be used to manage other cases, and it's up to you to build whichever helpers would make more sense for your case.

In my opinion, it's better to have those controls so you can manage your code rather than using something like `Eventually`, which usually means you need to rely on tickers or timeouts.

In my first example, you could even get rid of the select as long as the program would deadlock with no other runnable goroutines.

```go
foo := &mock.Foo{}
done := make(chan struct{})
foo.On("Foo", nil).Once().Run(func(mock.Arguments) { close(done) })
bar := NewBar(foo) //this runs a go routine that waits on a channel
bar.handleFoo(nil) //sends nil on bar's channel
<-done // this test is blocked until Foo is called, or panic and make the tests fail if all goroutines are asleep.
foo.AssertExpectations()
```

The select is a fallback to keep your tests from blocking a long time because the test has deadlocekd and there are some goroutines somewhere running.

Do you have proposal on how to handle this altenrantively and how it would work?

Regarding the second example, it only has a race if `bar` has no control over how handlers are called to tear everything down. It's common to have `Close` block until pending processing has been drained/cancelled and goroutines have stopped.

In order to talk about your actual code I would need to understand what problem you are solving and how :)

**Comment by georgelesica-wf** [comment]
Hello, my name is George. I've recently taken over maintenance of Testify and
I'm excited to help the project move forward.

In order to improve responsiveness and promote contributions to the Testify
project, I have decided to close pull requests and issues that haven't had any
activity in several months and do not appear to address critical bugs.

If you would still like to see your pull request or issue addressed, I am happy
to help! All you have to do is re-open and update it to reflect the current
state of the master branch. Once that is done, I will triage and recruit
reviewers as-needed.

If you have questions, please feel free to reach out. Thank you for your
interest in improving the Testify project!

**Comment by dolmen** [comment]
[`assert.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/assert#Eventually) now exists.
