### ISSUE TITLE
Do not vendor dependencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [stretchr/testify#328]
It is very rare that a library uses `vendor/` to vend dependencies. And if you do you are supposed to import them with full path like `github.com/stretchr/testifty/vendor/github.com/davecgh/go-spew/spew`.

Being a library and having vendored dependencies totally confuses dependency management tools like godep. Here is an example: https://github.com/tools/godep/issues/494 so please don't do it.

**Comment by albrow** [comment]
> And if you do you are supposed to import them with full path

It's a compiler error to import something from a vendor directory like that. This is true as of Go 1.6 (and possibly Go 1.5 as well).

Also from the [official documentation for the go command](https://golang.org/cmd/go/#hdr-Vendor_Directories):

> Code below a directory named "vendor" is importable only by code in the directory tree rooted at the parent of "vendor", and only using an import path that omits the prefix up to and including the vendor element.

**Comment by ernesto-jimenez** [comment]
Hi @ahmetalpbalkan @fgrosse @belak @onlyjob @panzerdev @guiltry @shoenig

We do want to vendor these dependencies since they are only used internally within testify. If one of our dependencies was pulled from github or released a version with breaking changes it is important for testify to keep working.

If you are using `godep`, you should be migrating to another tool like `go vendor`.

From the #godep channel in the Gophers Slack:

![screenshot 2016-09-24 20 02 51](https://cloud.githubusercontent.com/assets/1005/18810594/2ee3bab8-8292-11e6-8bfd-d4513656d230.png)
