### ISSUE TITLE
Please publish a new release/version tag

### ISSUE THREAD

**Issue by albrow** [stretchr/testify#336]
The last version to be released was [v1.1.3](https://github.com/stretchr/testify/releases/tag/v1.1.3) on January 9. There have been many commits since then. Tools such as [Glide](https://github.com/Masterminds/glide) and [gopkg.in](http://labix.org/gopkg.in) use these tags to satisfy semantic versioning constraints.

Could you please publish a new release/tag with the appropriate version (depending on whether or not backwards compatibility has been broken or new features have been introduced). Otherwise, if there is some reason you have not published a release in a while, would you mind clarifying?

**Comment by ernesto-jimenez** [comment]
I'm triaging issues and PRs.

Once I'm done today I'll tag a new version.

**Comment by ernesto-jimenez** [comment]
v1.1.4 is tagged

**Comment by albrow** [comment]
Thank you @ernesto-jimenez. Will you continue to tag new versions as changes are introduced in the future?

**Comment by ernesto-jimenez** [comment]
@albrow, yes.

We sometimes have to be reminded about it because most people use testify directly with the GitHub import path.

We just work to maintain the package stable backwards compatible, so the upside of tagging versions is pretty neglectible.

We'll keep tagging because it costs us nothing. Hopefully versioning in Go will get better in the future so we can actually make it a priority.

**Comment by albrow** [comment]
👌  appreciate it.
