### ISSUE TITLE
suite: plans to better support go1.7 subtests?

### ISSUE THREAD

**Issue by pkieltyka** [stretchr/testify#346]
Hello,

I really like the use of suite's and while using them with subtests, I ran into some nuances that made me think suite should be slightly refactored to work better with subtests. Just wondering about any thoughts/plans?

**Comment by ernesto-jimenez** [comment]
@pkieltyka did you refer to #341 ?

If so, it has been #343 has already been merged fixing it :)

**Comment by alecthomas** [comment]
I'm suspecting he meant refactoring suite to utilise subtests, making it more compatible with the stdlib.

**Comment by bayesianmind** [comment]
Yes, if suite used subtests it would nest nicely and allow you to run a suite multiple times with different params. The suite's results should nest under the suite run.
I am working on a PR to fix this.

As things are now (screenshots from Gogland):
<img width="502" alt="screen shot 2017-01-19 at 1 38 42 pm" src="https://cloud.githubusercontent.com/assets/2622905/22126696/9d0bd70c-de4d-11e6-9bb7-1686ff9fd061.png">

After my diff, subtests properly nest under the suite (meaning you could easily run the suite multiple times with different params and results are nicely attributed to the suite rather than just tacked on to the list):
<img width="564" alt="screen shot 2017-01-19 at 1 44 32 pm" src="https://cloud.githubusercontent.com/assets/2622905/22126705/a6ea54ba-de4d-11e6-95f3-1367b82a9922.png">
