### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by timkgh** [stretchr/testify#482]
There are a bunch of open issues and open PRs. Do they get looked at/merged on a regular basis?
Trying to decide if it's wise to rely on testify for new projects or it's become abandonware in favor of other frameworks and if so which.

**Comment by losinggeneration** [comment]
I can't speak for the maintainers. However, the commit log indicates it's still maintained. 
> Latest commit 05e8a0e 14 days ago

**Comment by lhemala** [comment]
The last release (v1.1.4) was cut on 25 Sep 2016 which is little annoying when you want to use `dep` with SemVer (and not simply pulling master) since a lot fixes were merged later later so yeah...
(For me it's https://github.com/stretchr/testify/issues/393)

So maybe if a maintainer stumbles across this:
Cutting a new realase after nearly a year seems like a good idea ;)

**Comment by reidrac** [comment]
The domain name of the org maintaining this repo is on sale, anyone knows what happened to Stretchr, Inc?

Some communication and/or a new release would be very appreciated!

**Comment by SophisticaSean** [comment]
Agreed, this looks abandoned.

**Comment by philtay** [comment]
New and active repo (forked): https://github.com/test-go/testify

**Comment by reidrac** [comment]
Any information re: the fork? Who's behind it?

**Comment by philtay** [comment]
Basically a group of volunteers. The project is seeking maintainers. ref. https://github.com/test-go/testify/issues/1

**Comment by ernesto-jimenez** [comment]
It is, and could do with some help: https://github.com/stretchr/testify/issues/526#issuecomment-353566941 

:)
