### ISSUE TITLE
Tagged Release?

### ISSUE THREAD

**Issue by xavi-** [stretchr/testify#494]
The last tagged release was back in Sept 2016, but there seems to have been a number of commits since then.  Any chance releases could be given semver friendly tags?

I ran into this issue when I ran `glide up` to get the latest and greatest, but ended up with a version that's nearly a year old.

**Comment by yurishkuro** [comment]
+1

**Comment by yiminc** [comment]
+1

**Comment by yiminc** [comment]
Our project https://github.com/uber-go/cadence-client depends on some of the new features added since last release tag. Now we have to pin to a hash version to make our code work. However, when our users needs to use our code, they run in to this issue and for every one of them, we have to told them to pin to that hash version. We need a new release!

**Comment by sagikazarmark** [comment]
I would like to second this request (not just +1). At least some response from the authors would be nice.

Finally Go packages reach an era when one can use properly versioned dependencies (glide, dep, etc), not just pull in the latest master (go get). I believe testify is one of the most required packages out there, so it would be nice to see that it follows the latest, best practices.

**Comment by philtay** [comment]
ping @ernesto-jimenez

**Comment by philtay** [comment]
New and active repo (forked): https://github.com/test-go/testify

**Comment by Hanzei** [comment]
There is a new release 1.2 (See https://github.com/stretchr/testify/releases/tag/v1.2.0)

**Comment by ernesto-jimenez** [comment]
And [v1.2.1](https://github.com/stretchr/testify/releases/tag/v1.2.1) now.

🙇
