### ISSUE TITLE
Gogland testing UI doesn't work with suite tests

### ISSUE THREAD

**Issue by varunrau** [stretchr/testify#512]
![image](https://user-images.githubusercontent.com/1448222/31641889-98e88282-b29c-11e7-9720-a1babf45e3f6.png)

It'd be great to be able to run/debug tests using the Gogland test runner. Currently the only way to do it is to run the whole suite.

**Comment by Vorte** [comment]
I am having the same problem but it seems the problem is in Gogland, not testify. Testify already supports running specific tests in a suite. 

https://godoc.org/github.com/stretchr/testify/suite - 'Regular expression to select the methods of test suites specified command-line argument "-m". '

We need better support for testify in Gogland as requested here: https://youtrack.jetbrains.com/issue/GO-3066

**Comment by ernesto-jimenez** [comment]
Thanks, as Vorte mentioned, testify does support it.

You would need to include the support in Gogland.
