### ISSUE TITLE
Support diff for strings

### ISSUE THREAD

**Issue by KingCrunch** [stretchr/testify#518]
When comparing strings

```
assert.Equals(t, "foo\nbar", "foo\nbaz")
```

it would be convenient to get the diff of both strings like one gets when comparing objects.

**Comment by nicolaiskogheim** [comment]
It's not nice, but I get the diff by converting strings to arrays.

```go
assert.Equals(t, strings.Split(expected, "\n"), strings.Split(actual, "\n"))
```

**Comment by ernesto-jimenez** [comment]
What should the output be like?

**Comment by nicolaiskogheim** [comment]
I suppose KingCrunch wants the string to be split on newlines so that the diff shows the "foo" part as equal and "bar" vs "baz" as a difference. That's what you get if you do like I did in my previous comment.

I often have two long strings (like some compact JSON), and to get a readable diff I have to prettify the JSON somehow and split the strings on newlines before I pass it to `assert.Equals`.

**Comment by ernesto-jimenez** [comment]
@nicolaiskogheim do you know about [assert.JSONEq](https://godoc.org/github.com/stretchr/testify/assert#JSONEq) ?

**Comment by nicolaiskogheim** [comment]
Nope! Look nice, though, thanks! 
Great that someone fixed the general issue as well.
