### ISSUE TITLE
Project migration, or ownership update

### ISSUE THREAD

**Issue by SophisticaSean** [stretchr/testify#526]
Hey all,

I, and many of my peers, use this repo a lot for testing. Could we update the membership to have people in it willing to merge some pull requests? I'd be happy to volunteer to maintain this repo. If not, we'll have to hard fork since there's currently 40 PR's open and the last commit happened 5 months ago. :( Releases need to be cut and improvements need to be made!

**Comment by nicolaiskogheim** [comment]
stretchrs website domain is for sale. Maybe the org is dead. Of all their repos, this is the one with the most recent commit.

**Comment by philtay** [comment]
It would be nice to have a "gotesting" GitHub organization with a (mantained) "testify" repo. Something like https://github.com/gotesting/testify.

**Comment by dignifiedquire** [comment]
@philtay I think this is a great idea to start an org to collect testing tools for go

I just created https://github.com/test-go/testify for this purpose, let me know if you want to help maintain this and I'll add you to the org

**Comment by dignifiedquire** [comment]
See https://github.com/test-go/testify/issues/1

**Comment by philtay** [comment]
@dignifiedquire Yep, add me. Although I don't have many cycles to spare I'm sick to see `testify` in this sorry state.

**Comment by dignifiedquire** [comment]
@philtay invite sent

**Comment by nilslice** [comment]
@dignifiedquire, @philtay, if you're looking for some more help, I would be happy to try my hand at some maintenance. We use the old stretchr repo for tons of our testing at work and this sounds more promising!

Feel free to throw an invite to the org my way if you'd like.

**Comment by dignifiedquire** [comment]
@nilslice invite sent, welcom

**Comment by ernesto-jimenez** [comment]
👋 sorry for the late reply.

Getting some help would be awesome!

What do you think would be the best way to open up contributions while being careful with backwards compatibility?

I had a new job and it has been crazy busy recently, which made it hard to properly review the PRs.

Since most people never used versioning, keeping testify backwards compatible is pretty critical, which means we need to be quite extra careful reviewing PRs:
* Guaranteeing backwards compatibility
* Making sure there's not behaviour changes
* Being mindful of what we export, since it we would be committing to it

Many of the requests we have received in the past were unfortunately backwards incompatible, and we had situations in the past where a seemingly innocuous change broke the build from a big project.

I did set time set aside next couple of weeks during my holidays to:
* Triage PRs and issues
* Outline guidelines to contribute backwards-compatible changes
* Clean up the notes I have about for v2: there are a quite a few changes that would be nice and would be backwards-incompatible. We also have github.com/gotestify for that.

It would be great to have help with all those three points:
* Triaging issues & PRs:
  * Answering to questions and closing those tickets
  * Requesting changes for PRs with failing CI
  * Labeling the issues and PRs that are backwards-incompatible as "Breaking Changes"
  * Flagging duplicates
  * Splitting fixes, vs new functionality
* Outline guidelines to contribute backwards-compatible changes: either taking a stab at a first draft or reviewing once it's drafted
* Testify v2:
  * It would be awesome to get some stats on testify usage: what packages and features are used the most. [It might be doable with BigQuery](https://medium.com/google-cloud/analyzing-go-code-with-bigquery-485c70c3b451)

If you want to chat, you can find me in the Gophers Slack: ernesto.

**Comment by ernesto-jimenez** [comment]
Closing this.

I have gone through most of the PRs today, made some changes I had pending, and released a new version. Hope to do some more work over the next few days.

If somebody wants to help, I would still appreciate help triaging the issues or addressing the PRs that got requests for changes.
