### ISSUE TITLE
ElementsMatch should ignore order for nested arrays

### ISSUE THREAD

**Issue by mntlty** [stretchr/testify#676]
ElementsMatch checks ordering in the struct fields of array elements.
This is surprising because I would expect ElementsMatch to ignore ordering for all fields, not just at the top level elements of an array.

Ex:

```Go
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

type N struct {
	Nums []int
}

// this one passes
func TestSameSubOrder(t *testing.T) {
	expected := []N{
		{
			Nums: []int{1, 2},
		},
	}
	actual := []N{
		{
			Nums: []int{1, 2},
		},
	}
	assert.ElementsMatch(t, expected, actual)
}

// this one fails
func TestReverseSubOrder(t *testing.T) {
	expected := []N{
		{
			Nums: []int{2, 1},
		},
	}
	actual := []N{
		{
			Nums: []int{1, 2},
		},
	}
	assert.ElementsMatch(t, expected, actual)
}
```

Running the tests:
```
$ go test
--- FAIL: TestReverseSubOrder (0.00s)
	assert_test.go:38: 
			Error Trace:	assert_test.go:38
			Error:      	element {[%!s(int=2) %!s(int=1)]} appears more times in [{[%!s(int=2) %!s(int=1)]}] than in [{[%!s(int=1) %!s(int=2)]}]
			Test:       	TestReverseSubOrder
FAIL
exit status 1
FAIL	_/test	0.016s
```

**Comment by srenatus** [comment]
🤔 I, too, would appreciate a matcher that does what ElementsMatch does in the recursive way outlined here. But I would think that keeping ElementsMatch as-is, and providing an alternative method would be a good way to go.

**Comment by msorens** [comment]
ElementsMatch is behaving correctly; here is why:
What it is tasked to do is determine if an array of elements `[A1, A2, A3, ... An]` are the same as elements `[B1, B2, B3, ... Bn]` while specifically ignoring order. This is different from normal array comparison where two arrays are equal if and only if the _corresponding_ elements are the same.

Note that this is different than comparing two _sets_, where order does not matter.
To say that two sets are the same, `{W1, W2, W3, ... Wn}` and `{Y1, Y2, Y3, ... Yn}`, one must always check in an order-independent fashion.

So let's say that ElementsMatch is looking at `A3` and `B24` and determining whether they are the same.
Say that each of these elements is an object with several properties including property `P`, where `P` is an array. For `A3.P` and `B24.P` to be the same they must, because they are arrays, have corresponding elements the same. Order matters.

While I quite agree it would be handy to have a matcher to compare arrays at _any_ level in an order-independent fashion, that is not what ElementsMatch does.

**Comment by benjamin-rood** [comment]
Sorry, but if I understand correctly, this decision was reversed, correct? `ElementsMatch` no longer requires matching ordering, i.e. it comparison it now uses is an _unordered, *set-style* comparison,_ correct?
