### ISSUE TITLE
Assert call order?

### ISSUE THREAD

**Issue by amoffat** [stretchr/testify#684]
Hi, great project.  Is there any way to assert the order that methods were called?  What's the best way to do it?  I'm assuming it is iterating over the mock's calls, and doing something, but I am imagining that the "something" means rewriting a lot of the argument checking logic by hand :)

Thanks!

**Comment by bkielbasa** [comment]
why do you need such a possibility?

**Comment by amoffat** [comment]
How do you check that a mock's methods were called in a specific order?  Sometimes your test is only correct if there is an ordering to events.

**Comment by bkielbasa** [comment]
IMO you should check the output of the function but not how it works internally. It may lead to testing implementation which is very hard to maintain.
For example, in the library https://github.com/DATA-DOG/go-sqlmock this methodology was used and because of that, in every case you use the library, you have to add proper assertions in the same order you have in the implementation. For me - it is complicated for more than 2 services with some logic and access to the DB.

**Comment by ran-berenfeld** [comment]
IMO there are cases to enforce order. i.e if you mock a mutex, you better check that Lock was always called before Unlock. We can have a simple implementation where the mock has an "assertExpectationsInOrder" true/false flag that can be set before any expectations are added.

**Comment by guenhter** [comment]
If you take a simple example like `io.ReadCloser`.
You want to assert that the `Close` function is called AFTER the read function and that no read happens any more if the close is already called.

**Comment by brackendawson** [comment]
This is covered under #741
