### ISSUE TITLE
Recover in suite

### ISSUE THREAD

**Issue by YaroslavDev** [stretchr/testify#695]
IMHO, panic in tests is not a good idea. Not only because it's hard to understand what test panicked, but panic also crashes entire test run and some tests don't even start. I think it's a good idea to isolate each test run by putting a defer/recover so that you know exactly what test caused panic and give possibility for other tests to run. 

Github PR implementing this feature: https://github.com/stretchr/testify/pull/696

**Comment by iaroslav-ciupin** [comment]
P.S.
If you want to test that some of your code panics as expected, you must explicitly put a recover in your test, catch actual panic and compare it with expected one. 
IMHO,
Panic **SHOULD NOT** propagate outside scope of a test case, because in a context of testing *panic is just another type of error* that should be caught and checked.

**Comment by itzamna314** [comment]
+1 to this.  With test suites that have some environmental setup/teardown, a panic will exit tests before the teardown can happen.  Then you've got resources you have to clean up manually.

Real-world example: I have a test suite that sets up a docker database container, then runs tests against it, and removes the container plus all volumes when everything is complete.  If I have a panic in my code, I have to manually go through and clear out the container and its volumes.

**Comment by YaroslavDev** [comment]
Merged
