### ISSUE TITLE
V Next?

### ISSUE THREAD

**Issue by ghostsquad** [stretchr/testify#756]
It looks like that last release was a few months ago, and there's so new code (reflected in godoc too), like `Greater` that is not yet available. Any plans on tagging a new version?

**Comment by BatmanAoD** [comment]
A few versions have been released since this issue was opened, but I've got the same question now (I want to be able to use `ErrorIs` and related). It might be helpful to have a regular release cadence.

**Comment by boyan-soubachov** [comment]
We try and keep a 6 month release cadence due to the sensitivity and widespread use of this package needing a good amount of time to gather user feedback and issues. `v1.7.0` is scheduled for December => https://github.com/stretchr/testify/milestones

If you would like to use the latest code (i.e. pre-release), just get master (e.g. `go get github.com/stretchr/testify@master`) or a commit hash (e.g. `@4fbbc112`) instead of `@master` to get up to a certain point.
