### ISSUE TITLE
Multilines don't play nicely with vim-go

### ISSUE THREAD

**Issue by shmup** [stretchr/testify#83]
I also opened the issue over there, but figured I'd additionally post here.

https://github.com/fatih/vim-go/issues/168

I attached two screenshots. One shows how `go test` renders in a terminal, and the other when using `:GoTest` within vim. I'm using testify mostly for assert functionality.

I chatted with fatih a bit in #go-nuts, and it was said that vim-go has pretty basic support for multilines. 

![screenshot 2014-09-09 19 46 45](https://cloud.githubusercontent.com/assets/118710/4210774/9de65f50-387b-11e4-9cd2-2eb506e3de66.png)
![screenshot 2014-09-09 19 47 40](https://cloud.githubusercontent.com/assets/118710/4210778/b27d73c2-387b-11e4-937f-0521506d25c9.png)

**Comment by yasker** [comment]
Would there be a update for this issue in the near future? It becomes the major reason currently I am reluctant to use testify. I just tried it and hit by this issue immediately, have to switch back to standard framework...

**Comment by nmiyake** [comment]
This affects running tests directly in IntelliJ as well.

I believe this is a real issue with alignment -- it has to do with outputting tabs instead of aligning properly via spaces for output. The update to put "expected:" and "received:" on different lines helps somewhat, but the issue still exists:

From terminal:

![image](https://cloud.githubusercontent.com/assets/4267425/19826061/66229a02-9d37-11e6-91c3-67c38c09f4eb.png)

Using IntelliJ runner:

![image](https://cloud.githubusercontent.com/assets/4267425/19826072/782f361a-9d37-11e6-8b5e-8337c131b241.png)

I have code that I believe fixes this -- it works in the IntelliJ runner and terminal, maintains the same output, and I believe it is more functionally correct. Will open as a PR shortly.

**Comment by rantav** [comment]
I have this issue as well (using vim-go), is there a fix for that?

**Comment by nmiyake** [comment]
@rantav can you check out my branch with the fix (https://github.com/nmiyake/testify/tree/fixFailOutput, which is the basis for the PR https://github.com/stretchr/testify/pull/364) and see if that resolves the issue? I can try to set up `vim-go` and see if I can repro the issue and if my fix addresses it.

I opened the potential fix PR in late October but unfortunately have not received any feedback on it yet.

**Comment by rantav** [comment]
Thanks @nmiyake but unfortunately for vim-go that still doesn't seem to work...

**Comment by sashaweiss** [comment]
Hey all - was there resolution on this, or a lasting workaround? Running into this myself currently, and it's driving me nuts.

**Comment by davidbanham** [comment]
@sashaweiss Yep, was fixed here:

https://github.com/stretchr/testify/commit/a726187e3128d0a0ec37f73ca7c4d3e508e6c2e5

**Comment by mrnugget** [comment]
Did something change in the meantime? I'm using vim-go 1.19 and the newest version of testify and `:GoTest` results in a `FAIL` message but an empty quickfix list.
