### ISSUE TITLE
testify/mock build is broken

### ISSUE THREAD

**Issue by procself** [stretchr/testify#854]
It seems that that the latest commit https://github.com/stretchr/testify/commit/7009337cb5726e58a8444528a492b85d111bc1a5 has broken the build of testift/mock.
I see this error:
	imports github.com/stretchr/testify/mock
	imports github.com/stretchr/objx: cannot find package "github.com/stretchr/objx" in any of:
	/usr/local/go/src/github.com/stretchr/objx (from $GOROOT)
	/go/src/github.com/stretchr/objx (from $GOPATH)

**Comment by glesica** [comment]
Looking into it.

**Comment by boyan-soubachov** [comment]
Will also take a look

**Comment by boyan-soubachov** [comment]
@procself , what is your `GO111MODULE` environment variable's value?

Could you tell us the exact steps you took to reproduce this error?

**Comment by procself** [comment]
@boyan-soubachov 
GO111MODULE is not set.
I'm building inside docker golang:1.12.1-stretch. First installing testify with 
go get -u github.com/stretchr/testify/assert
and finally running 'go test ...'

**Comment by lffloyd** [comment]
Hello,

I'm having the same problem with testify.

`imports github.com/stretchr/testify/mock
	imports github.com/stretchr/objx: cannot find package "github.com/stretchr/objx" in any of:
	/usr/local/go/src/github.com/stretchr/objx (from $GOROOT)
	/home/username/go/src/github.com/stretchr/objx (from $GOPATH)`

No solution yet?

**Comment by boyan-soubachov** [comment]
Hi, I haven't had a chance to look into this but will do so later today.

**Comment by boyan-soubachov** [comment]
@procself : I'm afraid I can't reproduce this. I did the following commands:

```
docker run -it golang:1.12.1-stretch
go get github.com/stretchr/testify/assert
cd github.com/stretchr/testify/assert
go test .
```
Please let me know if I've missed or left out something. If not, can you think of an alternate way I can reproduce this?

**Comment by boyan-soubachov** [comment]
@procself , I've managed to replicate the behaviour. It seems like the reason you're getting this behaviour is because you're explicitly `go get`-ing `github.com/stretchr/testify/assert`.

As the `assert` package doesn't have a `go.mod` (and is therefore, technically, not a go module). It only installs the dependencies it finds in its source files (of which `stretchr/objx` _is not_).

To fix this, you have to run `go get github.com/stretchr/testify`, that will install all dependencies of the base and sub-packages as listed in the `go.mod` and `go.sum` files.
